sudo: required

language: c

services:
- docker

before_install:
  - docker build -t joshymjose/debian:arm-gcc .
  - docker run -d --name test joshymjose/debian:arm-gcc
  - docker ps -a

script:
  - docker push joshymjose/debian:arm-gcc
