language: c

services:
- docker

before_install:
  - docker build -t joshymjose/debian:arm-gcc .
  - docker run -d -p 127.0.0.1:80:4567 --name test joshymjose/debian:arm-gcc
  - docker ps -a

script:
